# Generated by Django 5.1.4 on 2024-12-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('family_name', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.CharField(blank=True, max_length=120, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('address1', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('pincode', models.CharField(blank=True, max_length=120, null=True)),
                ('epic_pid', models.CharField(blank=True, max_length=120, null=True)),
                ('epic_response', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
