# Generated by Django 5.1.4 on 2024-12-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_org_id', models.CharField(blank=True, max_length=120, null=True)),
                ('org_name', models.CharField(blank=True, max_length=120, null=True)),
                ('address_line', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('pincode', models.CharField(blank=True, max_length=120, null=True)),
                ('org_mobile', models.CharField(blank=True, max_length=120, null=True)),
                ('org_email', models.CharField(blank=True, max_length=120, null=True)),
                ('epic_pid', models.CharField(blank=True, max_length=120, null=True)),
                ('epic_response', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
