# Generated by Django 5.1.4 on 2024-12-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapi', '0002_insuranceorganization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceorganization',
            old_name='epic_pid',
            new_name='epic_resp_id',
        ),
    ]
