# Generated by Django 5.1.4 on 2024-12-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi', '0004_insuranceorganization_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='epic_resp_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='epic_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
