# Generated by Django 5.1.4 on 2025-01-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi', '0005_coverage_epic_resp_id_coverage_epic_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPIPractitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi_name', models.CharField(blank=True, max_length=120, null=True)),
                ('family_name', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.CharField(blank=True, max_length=120, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('address1', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('pincode', models.CharField(blank=True, max_length=120, null=True)),
                ('epic_npi_id', models.CharField(blank=True, max_length=120, null=True)),
                ('epic_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
