# Generated by Django 5.1.4 on 2025-01-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapi', '0006_npipractitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='npi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hapi.npipractitioner'),
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(blank=True, max_length=120, null=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('net_amount', models.IntegerField(default=0)),
                ('claim_amount', models.IntegerField(default=0)),
                ('currency', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.BooleanField(default=False)),
                ('epic_resp_id', models.CharField(blank=True, max_length=120, null=True)),
                ('epic_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('coverage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hapi.coverage')),
                ('npi_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hapi.npipractitioner')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hapi.insuranceorganization')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hapi.patient')),
            ],
        ),
    ]
